//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました
//     ランタイム バージョン:2.0.50727.832
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2mKoubai.Shiiresaki {
    
    
    /// <summary>
    /// CtlTabShiire クラス
    /// </summary>
    /// <remarks>
    /// 自動生成されたクラス
    /// </remarks>
    public partial class CtlTabShiire {
        
        /// <summary>
        /// Tab コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::Telerik.WebControls.RadTabStrip Tab;
        
        /// <summary>
        /// Radtabstrip1 コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::Telerik.WebControls.RadTabStrip Radtabstrip1;
        
        /// <summary>
        /// TabLO コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::Telerik.WebControls.Tab TabLO;
    }
}
