//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました
//     ランタイム バージョン:2.0.50727.832
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2mKoubai.Master {
    
    
    /// <summary>
    /// LoginMsgUpForm クラス
    /// </summary>
    /// <remarks>
    /// 自動生成されたクラス
    /// </remarks>
    public partial class LoginMsgUpForm {
        
        /// <summary>
        /// form1 コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// TblAll コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TblAll;
        
        /// <summary>
        /// LblMsg コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LblMsg;
        
        /// <summary>
        /// BtnC コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton BtnC;
        
        /// <summary>
        /// TblMain コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TblMain;
        
        /// <summary>
        /// RbtnYukou コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton RbtnYukou;
        
        /// <summary>
        /// RbtnMukou コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton RbtnMukou;
        
        /// <summary>
        /// TbxMsg コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TbxMsg;
        
        /// <summary>
        /// TblBtn コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TblBtn;
        
        /// <summary>
        /// BtnT コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton BtnT;
        
        /// <summary>
        /// BtnK コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton BtnK;
        
        /// <summary>
        /// BtnTS コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button BtnTS;
        
        /// <summary>
        /// BtnKS コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button BtnKS;
    }
}
