//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました
//     ランタイム バージョン:2.0.50727.832
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2mKoubai.Master {
    
    
    /// <summary>
    /// TantoushaAccountUpForm クラス
    /// </summary>
    /// <remarks>
    /// 自動生成されたクラス
    /// </remarks>
    public partial class TantoushaAccountUpForm {
        
        /// <summary>
        /// Head1 コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlHead Head1;
        
        /// <summary>
        /// form1 コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// TblAll コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TblAll;
        
        /// <summary>
        /// LblMsg コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LblMsg;
        
        /// <summary>
        /// BtnC コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton BtnC;
        
        /// <summary>
        /// TblMain コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TblMain;
        
        /// <summary>
        /// TbxTCode コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TbxTCode;
        
        /// <summary>
        /// TbxTName コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TbxTName;
        
        /// <summary>
        /// TbxBusho コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TbxBusho;
        
        /// <summary>
        /// TbxYakushoku コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TbxYakushoku;
        
        /// <summary>
        /// TbxID コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TbxID;
        
        /// <summary>
        /// LitLoginID コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal LitLoginID;
        
        /// <summary>
        /// TbxPass コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TbxPass;
        
        /// <summary>
        /// TbxMail コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TbxMail;
        
        /// <summary>
        /// RbtnKanrisha コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton RbtnKanrisha;
        
        /// <summary>
        /// RbtnKanrishaNashi コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton RbtnKanrishaNashi;
        
        /// <summary>
        /// DdlJigyoushoKubun コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DdlJigyoushoKubun;
        
        /// <summary>
        /// TblBtn コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TblBtn;
        
        /// <summary>
        /// BtnT コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton BtnT;
        
        /// <summary>
        /// BtnK コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton BtnK;
        
        /// <summary>
        /// BtnTS コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button BtnTS;
        
        /// <summary>
        /// BtnKS コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button BtnKS;
    }
}
