//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました
//     ランタイム バージョン:2.0.50727.832
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2mKoubai.Common {
    
    
    /// <summary>
    /// CtlMyPager クラス
    /// </summary>
    /// <remarks>
    /// 自動生成されたクラス
    /// </remarks>
    public partial class CtlMyPager {
        
        /// <summary>
        /// T コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable T;
        
        /// <summary>
        /// BtnPrev コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button BtnPrev;
        
        /// <summary>
        /// DdlPage コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DdlPage;
        
        /// <summary>
        /// LitPageCount コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal LitPageCount;
        
        /// <summary>
        /// BtnNext コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button BtnNext;
        
        /// <summary>
        /// LitCounter コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal LitCounter;
    }
}
