//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.5477
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2mKoubai.Common {
    
    
    public partial class CtlNengappiFromTo {
        
        /// <summary>
        /// TblFrom コントロール。
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド。
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TblFrom;
        
        /// <summary>
        /// RdpFrom コントロール。
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド。
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
        /// </remarks>
        protected global::Telerik.WebControls.RadDatePicker RdpFrom;
        
        /// <summary>
        /// DdlKikan コントロール。
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド。
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DdlKikan;
        
        /// <summary>
        /// TblTo コントロール。
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド。
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TblTo;
        
        /// <summary>
        /// RdpTo コントロール。
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド。
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
        /// </remarks>
        protected global::Telerik.WebControls.RadDatePicker RdpTo;
    }
}
