//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました
//     ランタイム バージョン:2.0.50727.832
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2mKoubai {
    
    
    /// <summary>
    /// MessegeForm クラス
    /// </summary>
    /// <remarks>
    /// 自動生成されたクラス
    /// </remarks>
    public partial class MessegeForm {
        
        /// <summary>
        /// form1 コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// TblAll コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TblAll;
        
        /// <summary>
        /// LblMsg コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LblMsg;
        
        /// <summary>
        /// BtnC コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton BtnC;
        
        /// <summary>
        /// TblMsg コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TblMsg;
        
        /// <summary>
        /// TbxMsg コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TbxMsg;
        
        /// <summary>
        /// BtnClear コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton BtnClear;
        
        /// <summary>
        /// BtnT コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton BtnT;
        
        /// <summary>
        /// G コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView G;
        
        /// <summary>
        /// BtnReg コントロール
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド
        /// 変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button BtnReg;
    }
}
